"""create procuradores and projetistas tables

Revision ID: 0b68062b8749
Revises: 397fc6f3cb23
Create Date: 2026-03-19 18:38:11.423737

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0b68062b8749'
down_revision: Union[str, Sequence[str], None] = '397fc6f3cb23'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('procuradores',
    sa.Column('id_procurador', sa.Integer(), nullable=False),
    sa.Column('nome_procurador', sa.String(), nullable=False),
    sa.Column('cpf_procurador', sa.String(), nullable=False),
    sa.Column('rg_procurador', sa.String(), nullable=False),
    sa.Column('telefone_procurador', sa.String(), nullable=False),
    sa.Column('email_procurador', sa.String(), nullable=False),
    sa.Column('logradouro_procurador', sa.String(), nullable=False),
    sa.Column('numero_casa_procurador', sa.String(), nullable=False),
    sa.Column('complemento_procurador', sa.String(), nullable=True),
    sa.Column('cep_procurador', sa.String(), nullable=False),
    sa.Column('bairro_procurador', sa.String(), nullable=False),
    sa.Column('cidade_procurador', sa.String(), nullable=False),
    sa.Column('estado_procurador', sa.String(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id_procurador')
    )
    op.create_table('projetistas',
    sa.Column('id_projetista', sa.Integer(), nullable=False),
    sa.Column('nome_projetista', sa.String(), nullable=False),
    sa.Column('creci_projetista', sa.String(), nullable=False),
    sa.Column('rubrica_projetista', sa.String(), nullable=False),
    sa.Column('telefone_projetista', sa.String(), nullable=False),
    sa.Column('email_projetista', sa.String(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id_projetista')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('projetistas')
    op.drop_table('procuradores')
    # ### end Alembic commands ###
