"""create projeto table and update relationships

Revision ID: 2545bf14df22
Revises: 7668e34fdb38
Create Date: 2026-03-19 23:54:44.691106

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2545bf14df22'
down_revision: Union[str, Sequence[str], None] = '7668e34fdb38'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('projetos',
    sa.Column('id_projeto', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=False),
    sa.Column('procurador_id', sa.Integer(), nullable=False),
    sa.Column('projetista_id', sa.Integer(), nullable=True),
    sa.Column('inversor_1_id', sa.Integer(), nullable=True),
    sa.Column('inversor_2_id', sa.Integer(), nullable=True),
    sa.Column('inversor_3_id', sa.Integer(), nullable=True),
    sa.Column('placa_1_id', sa.Integer(), nullable=True),
    sa.Column('placa_2_id', sa.Integer(), nullable=True),
    sa.Column('placa_3_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.id_cliente'], ),
    sa.ForeignKeyConstraint(['inversor_1_id'], ['inversores.id_inversor'], ),
    sa.ForeignKeyConstraint(['inversor_2_id'], ['inversores.id_inversor'], ),
    sa.ForeignKeyConstraint(['inversor_3_id'], ['inversores.id_inversor'], ),
    sa.ForeignKeyConstraint(['placa_1_id'], ['placas.id_placa'], ),
    sa.ForeignKeyConstraint(['placa_2_id'], ['placas.id_placa'], ),
    sa.ForeignKeyConstraint(['placa_3_id'], ['placas.id_placa'], ),
    sa.ForeignKeyConstraint(['procurador_id'], ['procuradores.id_procurador'], ),
    sa.ForeignKeyConstraint(['projetista_id'], ['projetistas.id_projetista'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id_projeto')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('projetos')
    # ### end Alembic commands ###
