"""create inversores and placas tables

Revision ID: 397fc6f3cb23
Revises: e4af398e955b
Create Date: 2026-03-19 18:23:48.539543

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '397fc6f3cb23'
down_revision: Union[str, Sequence[str], None] = 'e4af398e955b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('inversores',
    sa.Column('id_inversor', sa.Integer(), nullable=False),
    sa.Column('marca_inversor', sa.String(), nullable=False),
    sa.Column('modelo_inversor', sa.String(), nullable=False),
    sa.Column('potencia_inversor', sa.Float(), nullable=False),
    sa.Column('numero_fases', sa.Enum('MONOFASICO', 'BIFASICO', 'TRIFASICO', name='tensao_fase'), nullable=False),
    sa.Column('tipo_de_inversor', sa.Enum('STRING', 'MICRO', name='tipo_inversor'), nullable=False),
    sa.Column('numero_mppt', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id_inversor')
    )
    op.create_table('placas',
    sa.Column('id_placa', sa.Integer(), nullable=False),
    sa.Column('marca_placa', sa.String(), nullable=False),
    sa.Column('modelo_placa', sa.String(), nullable=False),
    sa.Column('potencia_placa', sa.Float(), nullable=False),
    sa.Column('tipo_celula', sa.String(), nullable=False),
    sa.Column('tensao_pico', sa.Float(), nullable=False),
    sa.Column('corrente_curtocircuito', sa.Float(), nullable=False),
    sa.Column('tensao_maxima_potencia', sa.Float(), nullable=False),
    sa.Column('corrente_maxima_potencia', sa.Float(), nullable=False),
    sa.Column('eficiencia_placa', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id_placa')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('placas')
    op.drop_table('inversores')
    # ### end Alembic commands ###
