"""create enderecocliente and enderecoobra tables

Revision ID: 7668e34fdb38
Revises: 0b68062b8749
Create Date: 2026-03-19 23:45:36.943940

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7668e34fdb38'
down_revision: Union[str, Sequence[str], None] = '0b68062b8749'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('enderecocliente',
    sa.Column('id_endereco_cliente', sa.Integer(), nullable=False),
    sa.Column('logradouro_cliente', sa.String(), nullable=False),
    sa.Column('numero_casa_cliente', sa.String(), nullable=False),
    sa.Column('complemento_casa_cliente', sa.String(), nullable=True),
    sa.Column('cep_cliente', sa.String(), nullable=False),
    sa.Column('bairro_cliente', sa.String(), nullable=False),
    sa.Column('cidade_cliente', sa.String(), nullable=False),
    sa.Column('estado_cliente', sa.String(), nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.id_cliente'], ),
    sa.PrimaryKeyConstraint('id_endereco_cliente')
    )
    op.create_table('enderecoobra',
    sa.Column('id_endereco_obra', sa.Integer(), nullable=False),
    sa.Column('logradouro_obra', sa.String(), nullable=False),
    sa.Column('numero_obra', sa.String(), nullable=False),
    sa.Column('complemento_obra', sa.String(), nullable=True),
    sa.Column('cep_obra', sa.String(), nullable=False),
    sa.Column('bairro_obra', sa.String(), nullable=False),
    sa.Column('cidade_obra', sa.String(), nullable=False),
    sa.Column('estado_obra', sa.String(), nullable=False),
    sa.Column('latitude_obra', sa.String(), nullable=True),
    sa.Column('longitude_obra', sa.String(), nullable=True),
    sa.Column('cliente_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.id_cliente'], ),
    sa.PrimaryKeyConstraint('id_endereco_obra')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('enderecoobra')
    op.drop_table('enderecocliente')
    # ### end Alembic commands ###
